name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint || true
      
    - name: Build frontend
      run: npm run build
  
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        python -m pytest || echo "No tests found"
        
    - name: Lint Python code
      run: |
        cd backend
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
  
  # Simple build job with minimal configuration
  simple-build:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Echo test
      run: echo "This is a simple test step"
  
  # More complete build job with build and artifact steps  
  build-artifacts:
    runs-on: ubuntu-latest
    needs: [simple-build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build frontend
      run: npm run build
        
    - name: Debug directory contents
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Dist directory contents:"
        ls -la dist || echo "No dist directory found"
        
    - name: Archive frontend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: dist
        if-no-files-found: warn
    
  # Final working version of the build and artifacts job
  build-and-push:
    name: Build and Create Artifacts
    needs: [frontend-test, backend-test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install frontend dependencies
      run: npm ci
      
    - name: Build frontend
      run: npm run build
      
    - name: Debug directory contents
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Dist directory contents:"
        ls -la dist || echo "No dist directory found"
    
    - name: Archive frontend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: dist
        
    - name: Archive backend code
      uses: actions/upload-artifact@v4
      with:
        name: backend-code
        path: backend 