name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint || true
      
    - name: Build frontend
      run: npm run build
  
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        python -m pytest || echo "No tests found"
        
    - name: Lint Python code
      run: |
        cd backend
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
  
  # Simple build job with minimal configuration
  simple-build:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Echo test
      run: echo "This is a simple test step"
  
  # More complete build job with build and artifact steps  
  build-artifacts:
    runs-on: ubuntu-latest
    needs: [simple-build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build frontend
      run: npm run build
        
    - name: Debug directory contents
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Dist directory contents:"
        ls -la dist || echo "No dist directory found"
        
    - name: Archive frontend artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-dist
        path: dist
        if-no-files-found: warn
    
  # Temporarily commented out for debugging
  # build-and-push:
  #   name: Build and Create Artifacts
  #   needs: [frontend-test, backend-test]
  #   # Only run this job if we're on main branch (not on PRs)
  #   if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0  # Full history for potential versioning
  #   
  #   - name: Debug environment
  #     run: |
  #       pwd
  #       ls -la
  #       echo "GitHub ref: ${{ github.ref }}"
  #       echo "Event name: ${{ github.event_name }}"
  #   
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18'
  #       cache: 'npm'  # Cache npm dependencies
  #   
  #   - name: Install frontend dependencies
  #     run: npm ci
  #     
  #   - name: Build frontend
  #     run: |
  #       npm run build
  #       echo "Build completed. Contents of current directory:"
  #       ls -la
  #       echo "Contents of dist directory (if it exists):"
  #       ls -la dist || echo "No dist directory found"
  #   
  #   - name: Archive frontend production artifacts
  #     if: success()
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: frontend-dist
  #       path: dist
  #       retention-days: 7
  #       
  #   - name: Archive backend code
  #     if: success()
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: backend-code
  #       path: backend
  #       retention-days: 7 